services:
  # 🐘 Veritabanı (PostgreSQL)
  postgres_db:
    image: postgres:18.3-alpine3.23
    restart: always
    ports:
      - "5432:5432"
    container_name: epiknovel_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Postgres 18+ için doğru mount dizini:
      - postgres_data_v18:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 🚄 Önbellek & Oturum (Redis)
  redis_cache:
    image: redis:8-alpine
    restart: always
    container_name: epiknovel_cache
    volumes:
      - redis_data:/data

  # 🚀 Ana API
  epiknovel_api:
    build:
      context: .
      dockerfile: Epiknovel.api/Dockerfile
    restart: always
    container_name: epiknovel_api
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_started
    volumes:
      - ./Uploads:/app/wwwroot/uploads
      - ./SecureDocs:/app/SecureDocs
      - ./Keys:/app/Keys
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION: ${DB_CONNECTION}
      REDIS_CONNECTION: ${REDIS_CONNECTION}
      JWT_SECRET: ${JWT_SECRET}
      Jwt__Secret: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      MEDIATR_LICENSE_KEY: ${MEDIATR_LICENSE_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_ENABLE_SSL: ${SMTP_ENABLE_SSL}

  # 💻 Kullanıcı Arayüzü (Next.js)
  epiknovel_web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    container_name: epiknovel_web
    ports:
      - "3000:3000"
    depends_on:
      - epiknovel_api
    environment:
      - NODE_ENV=production
      - API_BASE_URL=https://api.epiknovel.com/api
      - NEXT_PUBLIC_COOKIE_SECURE=true

  # 🛡️ Ters Proxy (Caddy)
  caddy:
    image: caddy:2-alpine
    restart: always
    container_name: epiknovel_proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - epiknovel_api
      - epiknovel_web
      - seq

  # 📊 Log Yönetimi (Seq)
  seq:
    image: datalust/seq:latest
    restart: always
    container_name: epiknovel_logs
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASSWORD}
    volumes:
      - seq_data:/data

volumes:
  postgres_data_v18:
  redis_data:
  epiknovel_keys:
  caddy_data:
  caddy_config:
  seq_data:
